// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiteJ_1P3pQ-O8ZNgLrvnDHSViQGgKNJQ',
    appId: '1:751797845424:web:2fb3235cc4074b15812a75',
    messagingSenderId: '751797845424',
    projectId: 'flutter-and-demo',
    authDomain: 'flutter-and-demo.firebaseapp.com',
    databaseURL: 'https://flutter-and-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-and-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4q_CjNY8ya_4ZT4Vd2vYW0z8MW6yWfMc',
    appId: '1:751797845424:android:308f08b6900ee667812a75',
    messagingSenderId: '751797845424',
    projectId: 'flutter-and-demo',
    databaseURL: 'https://flutter-and-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-and-demo.appspot.com',
  );
}
